site_name: daemonless CI
site_url: https://ci.daemonless.io

theme:
  name: material
  logo: assets/daemonless-logo.svg
  favicon: assets/favicon.ico
  palette:
    scheme: slate
    primary: deep orange

nav:
  - Status: index.md
